clc;
clear all;
rows_a=3;
columns_a=33;
rows_b=33;
columns_b=3;
a=rand(rows_a, columns_a);
b=rand(rows_b, columns_b);
c= a * b;
c(1:size(c,1)+1:end) = 0;
disp('matrix after replacing diagonalelement with the zero');
disp(c);